### ISSUE TITLE
安卓设备获取fps数据失败

### ISSUE THREAD

**Issue by DianMoC** [smart-test-ti/SoloX#120]
[E 230316 14:39:33 fps:310] an exception hanpend in fps _collector_thread , reason unkown!
[D 230316 14:39:33 fps:312] Traceback (most recent call last):
      File "C:\Install\Anaconda3\lib\site-packages\solox\public\fps.py", line 280, in _collector_thread
        refresh_period, new_timestamps = self._get_surfaceflinger_frame_data()
      File "C:\Install\Anaconda3\lib\site-packages\solox\public\fps.py", line 426, in _get_surfaceflinger_frame_data
        self.focus_window = self.get_huawei_activity()
      File "C:\Install\Anaconda3\lib\site-packages\solox\public\fps.py", line 81, in get_huawei_activity
        activity_name = activity_line_split[2]
    IndexError: list index out of range
    
activity_line_split: 
获取fps数据失败了

**Comment by rafa0128** [comment]
adb shell dumpsys SurfaceFlinger --list | grep [包名]
执行发出来看看，提问题麻烦说下solox版本、什么机型系统版本

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/issues/49
请按要求提问题
