### ISSUE TITLE
Failed to Connect iOS Device

### ISSUE THREAD

**Issue by Sivasankaramalan** [smart-test-ti/SoloX#136]
Issue:
Solox is not detecting the  iOS device

Logs:
`  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10.60.14.38 - - [03/Apr/2023 14:12:45] "GET /device/ids?platform=iOS&_=1680511361538 HTTP/1.1" 200 -
/bin/sh: /usr/local/bin/tidevice: /usr/local/opt/python@3.11/bin/python3.11: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/view/apis.py", line 69, in deviceids
    deviceinfos = d.getDeviceInfoByiOS()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/public/common.py", line 101, in getDeviceInfoByiOS
    deviceResult = json.loads(self.execCmd('tidevice list --json'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10.60.14.38 - - [03/Apr/2023 14:12:48] "GET /device/ids?platform=iOS&_=1680511361539 HTTP/1.1" 200 -
`

<img width="590" alt="image" src="https://user-images.githubusercontent.com/34656428/229458809-a3886049-92ab-4fa5-93d8-d2a968da6213.png">

**Comment by rafa0128** [comment]
What is your PC machine? Windows or Mac?  
https://github.com/smart-test-ti/SoloX/discussions/108

**Comment by Sivasankaramalan** [comment]
This is in Mac (M1-Apple Silicon)

**Comment by rafa0128** [comment]
I guess your Mac may have failed to install tidevice. You can try "pip install tidevice=0.9.7" on the terminal

**Comment by Sivasankaramalan** [comment]
let me install and check

**Comment by Sivasankaramalan** [comment]
Still, same issue, tried reinstalling the SoloX. but it's not able to fetch the device details. Please find the logs below. 

`/bin/sh: /usr/local/bin/tidevice: /usr/local/opt/python@3.11/bin/python3.11: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/view/apis.py", line 81, in deviceids
    deviceinfos = d.getDeviceInfoByiOS()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/public/common.py", line 105, in getDeviceInfoByiOS
    deviceResult = json.loads(self.execCmd('tidevice list --json'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Sivasankaramalan** [comment]
Installed Libraries:
<img width="1504" alt="Screenshot 2023-04-05 at 2 05 55 PM" src="https://user-images.githubusercontent.com/34656428/230027927-bf2b2d74-bf53-47e4-818e-4ee2880e2cc4.png">

**Comment by Sivasankaramalan** [comment]
This is the issue with tidevice, resolved this issue by cleaning up the directory. thank you!
