### ISSUE TITLE
python3 -m solox 报错

### ISSUE THREAD

**Issue by cjckkk** [smart-test-ti/SoloX#143]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/junchengchen/Downloads/SoloX-2.6.0/solox/__main__.py", line 2, in <module>
    from solox.web import main
  File "/Users/junchengchen/Downloads/SoloX-2.6.0/solox/web.py", line 13, in <module>
    from solox.view.apis import api
  File "/Users/junchengchen/Downloads/SoloX-2.6.0/solox/view/apis.py", line 66
    match(platform):
                    ^
SyntaxError: invalid syntax

**Comment by rafa0128** [comment]
python版本低了，看安装说明

**Comment by cjckkk** [comment]
3.9还低？

**Comment by rafa0128** [comment]
> 3.9还低？

看安装说明不要杠，3.10和3.9的特性不同

**Comment by cjckkk** [comment]
work 感谢
