### ISSUE TITLE
你好我的mac连接ios后报错 get fps failed，只能获取到电量，求大佬帮忙解决下 

### ISSUE THREAD

**Issue by chenhezhong666** [smart-test-ti/SoloX#145]
![image](https://user-images.githubusercontent.com/24536938/234004604-bbb66048-59ba-4ad6-a1f0-0445fe34f3d5.png)
[E 230424 21:01:06 apis:302] get fps failed
Traceback (most recent call last):
  File "/Users/chenhezhong/Project/SoloX/solox/view/apis.py", line 299, in getFps
    fps, jank = fps_monitor.getFPS()
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhezhong/Project/SoloX/solox/public/apm.py", line 288, in getFPS
    fps, jank = self.getAndroidFps(noLog) if self.platform == Platform.Android else self.getiOSFps(noLog)
                                                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhezhong/Project/SoloX/solox/public/apm.py", line 280, in getiOSFps
    fps = int(apm.getPerformance(apm.fps))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhezhong/Project/SoloX/solox/public/apm.py", line 336, in getPerformance
    perf_value = perf.start(self.pkgName, callback=self.callback)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhezhong/Project/SoloX/solox/public/_iosPerf.py", line 322, in start
    _perfValue = self._thread_start(callback)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhezhong/Project/SoloX/solox/public/_iosPerf.py", line 342, in _thread_start
    _perfValue = append_data(self._wg, self._stop_event, it, callback, self._perfs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhezhong/Project/SoloX/solox/public/_iosPerf.py", line 274, in append_data
    for _type, data in idata:
  File "/Users/chenhezhong/Project/SoloX/solox/public/_iosPerf.py", line 107, in iter_fps
    with d.instruments_context() as ts:
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BaseDevice' object has no attribute 'instruments_context'

![image](https://user-images.githubusercontent.com/24536938/234005006-995faa70-121a-4411-ad3c-7eaac6176918.png)
![image](https://user-images.githubusercontent.com/24536938/234005044-8047b91e-6bb8-4899-8ce1-c695c0b515da.png)

**Comment by rafa0128** [comment]
你是自己拉代码改了吗？看看import模块有没有问题

**Comment by chenhezhong666** [comment]
没有 方便给远程看下吗 微信chz920922750

**Comment by rafa0128** [comment]
不加微信哦，应该动代码了，看你的调用不可能没改代码，_iosPerf.py这个文件顶部的import截图看看，

**Comment by chenhezhong666** [comment]
![image](https://user-images.githubusercontent.com/24536938/234016622-e9f24159-766c-4ec3-93b5-ae80d2f553d4.png)
帮忙看下 真的没动代码

**Comment by rafa0128** [comment]
这还看不出吗，你没装solox

**Comment by rafa0128** [comment]
严格按照文档操作即可，文档都有要求
