### ISSUE TITLE
运行debug.py报错

### ISSUE THREAD

**Issue by loneyao** [smart-test-ti/SoloX#148]
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 /Users/mac/Downloads/SoloX-master/solox/debug.py
Traceback (most recent call last):
  File "/Users/mac/Downloads/SoloX-master/solox/debug.py", line 17, in <module>
    from flask_socketio import SocketIO, disconnect
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_socketio/__init__.py", line 24, in <module>
    from werkzeug.serving import run_with_reloader
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/werkzeug/serving.py)

mas os 11
python 3.10.11

**Comment by rafa0128** [comment]
模块应该没有安装好，但这个文件不是给你们用的。按照README文档安装和运行，不要自己捣鼓
