### ISSUE TITLE
Mac，iPhone13无法监测到CPU、GPU、Network、MEM

### ISSUE THREAD

**Issue by chenyan77240** [smart-test-ti/SoloX#151]
Mac Pro：12.4
iPhone 13 ：16.3.1
Python： 3.11
通过python3 -m solox 启动，已连接IOS设备选择QQ音乐，点击开始后会弹窗报错Host Error，host is invalid；但是继续操作QQ音乐，能看到FPS图有变化，其他CPU、GPU、Network、MEM等指标无法监测到，点击结束生成报告会一直卡住提示生成报告页，求大神指导~

命令行日志中报错：cpu、mem请求返回400错误，GPU.__init__() got an unexpected keyword argument 'pkgname'，但是从界面上已选了QQ音乐应用

192.168.1.11 - - [29/Apr/2023 10:49:38] "GET /package/pids?platform=iOS&device=iPhoneSE%3Ae393b6f72bd4d0332811e7b795907c304bb1bbd7&pkgname=com.tencent.QQMusic&_=1682736572708 HTTP/1.1" 200 -
192.168.1.11 - - [29/Apr/2023 10:49:40] "GET /apm/set/network?platform=iOS&pkgname=com.tencent.QQMusic&device=iPhoneSE%3Ae393b6f72bd4d0332811e7b795907c304bb1bbd7&wifi_switch=false&type=pre&_=1682736572709 HTTP/1.1" 400 -
192.168.1.11 - - [29/Apr/2023 10:49:40] "POST /apm/initialize HTTP/1.1" 200 -
192.168.1.11 - - [29/Apr/2023 10:49:40] "GET /apm/cpu?model=normal&platform=iOS&pkgname=com.tencent.QQMusic&device=iPhoneSE%3Ae393b6f72bd4d0332811e7b795907c304bb1bbd7&_=1682736572710 HTTP/1.1" 400 -
192.168.1.11 - - [29/Apr/2023 10:49:40] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.tencent.QQMusic&device=iPhoneSE%3Ae393b6f72bd4d0332811e7b795907c304bb1bbd7&_=1682736572711 HTTP/1.1" 400 -
192.168.1.11 - - [29/Apr/2023 10:49:40] "GET /apm/network?model=normal&platform=iOS&pkgname=com.tencent.QQMusic&device=iPhoneSE%3Ae393b6f72bd4d0332811e7b795907c304bb1bbd7&wifi_switch=false&_=1682736572712 HTTP/1.1" 400 -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/view/apis.py", line 336, in getGpu
    gpu = GPU(pkgname=pkgname)
          ^^^^^^^^^^^^^^^^^^^^
TypeError: GPU.__init__() got an unexpected keyword argument 'pkgname'

<img width="1440" alt="启动报错Host Error" src="https://user-images.githubusercontent.com/5500551/235171695-062b311e-ef0a-474b-b113-9482eaef1a57.png">
<img width="1440" alt="CPU和MEM为空" src="https://user-images.githubusercontent.com/5500551/235171729-d1a58e68-d2a6-487e-9772-62ef07dd4989.png">
<img width="1440" alt="仅获取到电池指标" src="https://user-images.githubusercontent.com/5500551/235171741-584d16c0-a55a-4d2f-9bf6-8ed860f8e9d7.png">
<img width="1440" alt="结束后一直卡在这个弹窗页" src="https://user-images.githubusercontent.com/5500551/235171754-4d709944-034d-4119-96bb-61aba3187477.png">
<img width="1440" alt="命令行错误" src="https://user-images.githubusercontent.com/5500551/235172199-f30b6ff6-c347-4595-a168-8e4e3c92b952.png">

**Comment by rafa0128** [comment]
这里有两个问题，gpu那个新版本解决了，另外一个是tidevice的问题，我建议你换个设备再试试看

**Comment by RockyAo** [comment]
我也有相同的问题， Solox 使用的master分之， Python 3.10.0， 我手里的所有设备都会出这个问题

**Comment by chenyan77240** [comment]
换IOS设备后，还是获取不到CPU、Mem指标

报错如下：看起来是Python的错误
[E 230521 19:14:37 apis:237] get memory data failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tidevice/_instruments.py", line 566, in wait_reply
    ret = self._reply_queues[message_id].get(timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty


[E 230521 17:46:59 apis:199] get cpu failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tidevice/_instruments.py", line 566, in wait_reply
    ret = self._reply_queues[message_id].get(timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

**Comment by rafa0128** [comment]
> 换IOS设备后，还是获取不到CPU、Mem指标
> 
> 报错如下：看起来是Python的错误 [E 230521 19:14:37 apis:237] get memory data failed Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tidevice/_instruments.py", line 566, in wait_reply ret = self._reply_queues[message_id].get(timeout=timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 179, in get raise Empty _queue.Empty
> 
> [E 230521 17:46:59 apis:199] get cpu failed Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tidevice/_instruments.py", line 566, in wait_reply ret = self._reply_queues[message_id].get(timeout=timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 179, in get raise Empty _queue.Empty

应该不是必然出现的吧？这个是tidevice的问题：https://github.com/alibaba/taobao-iphone-device/issues/215
