### ISSUE TITLE
无法连接ios16 

### ISSUE THREAD

**Issue by G-chunyang** [smart-test-ti/SoloX#174]
tidevice list 能查看连接的ip13pro，点连接提示连接失败。

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice\__main__.py", line 978, in main
    actions[args.subparser](args)
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice\__main__.py", line 111, in cmd_list
    _print_json(result)
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice\__main__.py", line 123, in _print_json
    print(json.dumps(value, indent=4, ensure_ascii=False, default=_bytes_hook))
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f479' in position 108: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\view\apis.py", line 76, in deviceids
    deviceinfos = d.getDeviceInfoByiOS()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\common.py", line 107, in getDeviceInfoByiOS
    deviceResult = json.loads(self.execCmd('tidevice list --json'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23123\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
192.168.2.104 - - [29/Jun/2023 15:48:59] "GET /device/ids?platform=iOS&_=1688024938387 HTTP/1.1" 200 -

**Comment by rafa0128** [comment]
tidevice list结果发出来看看

**Comment by G-chunyang** [comment]
<img width="772" alt="Snipaste_2023-06-29_17-47-51" src="https://github.com/smart-test-ti/SoloX/assets/48399416/bf7befb9-5ca2-4319-9ae0-08d994af272e">

**Comment by rafa0128** [comment]
tidevice list --json 用这个命令，看看输出是不是一个json，报错说结果不是json

**Comment by G-chunyang** [comment]
<img width="346" alt="Snipaste_2023-06-29_18-06-43" src="https://github.com/smart-test-ti/SoloX/assets/48399416/44ac63f0-0fd7-4712-ab11-7e572382359e">
 麻烦帮看下

**Comment by rafa0128** [comment]
> <img alt="Snipaste_2023-06-29_18-06-43" width="346" src="https://user-images.githubusercontent.com/48399416/249741332-44ac63f0-0fd7-4712-ab11-7e572382359e.png"> 麻烦帮看下

复制文本发出来，可以改掉你的设备信息，整体结构不要改

**Comment by G-chunyang** [comment]
C:\Users\23123>tidevice list --json
[
    {
        "udid": "0000xxxxx91801E",
        "serial": "HWxxxxx2WYG",
        "name": "欧阳👹",
        "market_name": "iPhone 13 Pro",
        "product_version": "16.3",
        "conn_type": "usb"
    }
]

C:\Users\23123>

**Comment by G-chunyang** [comment]
[
    {
        "udid": "00008110-00016D622291801E",
        "serial": "HW06QR2WYG",
        "name": "欧阳👹",
        "market_name": "iPhone 13 Pro",
        "product_version": "16.3",
        "conn_type": "usb"
    }
]

**Comment by rafa0128** [comment]
下个版本修复

**Comment by G-chunyang** [comment]
把设备名字的emoji删除，可以连接了。期待下版本修复~⭐⭐⭐
