### ISSUE TITLE
连不上设备

### ISSUE THREAD

**Issue by cmttttttt** [smart-test-ti/SoloX#186]
我是win10，装的2.5.7的版本iOS和安卓都连不上，提示“连接失败”

**Comment by rafa0128** [comment]
就一句话叫我怎么办

**Comment by rafa0128** [comment]
要提供报错日志，连接失败一般是环境没有弄好，仔细看文档

**Comment by 986379041** [comment]
我也连不上：
[E 230809 19:53:28 apis:88] 'utf-8' codec can't decode byte 0xb2 in position 56: invalid start byte
    Traceback (most recent call last):
      File "D:\Program Files\Python\Python310\lib\site-packages\solox\view\apis.py", line 76, in deviceids
        pkgnames = d.getPkgnameByiOS(deviceinfos[0].split(':')[1])
      File "D:\Program Files\Python\Python310\lib\site-packages\solox\public\common.py", line 117, in getPkgnameByiOS
        pkgResult = self.execCmd(f'tidevice --udid {udid} applist').split('\n')
      File "D:\Program Files\Python\Python310\lib\site-packages\solox\public\common.py", line 32, in execCmd
        text = r.buffer.read().decode(encoding='utf-8').strip()
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 56: invalid start byte

**Comment by rafa0128** [comment]
> 

更新solox最新的版本
