### ISSUE TITLE
python3.11 -m solox  不能打开页面

### ISSUE THREAD

**Issue by lishun001** [smart-test-ti/SoloX#198]
**
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/__main__.py", line 17, in <module>
    from solox.web import main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/web.py", line 112, in <module>
    def main(host=ip(), port=50003):
                  ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/web.py", line 69, in ip
    ip = socket.gethostbyname(socket.gethostname())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
**

**Comment by rafa0128** [comment]
> 
https://apple.stackexchange.com/questions/253817/cannot-ping-my-local-machine

**Comment by rafa0128** [comment]
> 
https://apple.stackexchange.com/questions/253817/cannot-ping-my-local-machine

**Comment by rafa0128** [comment]
先短暂按照上面的文档处理一下，我后面兼容mac的这种情况

**Comment by rafa0128** [comment]
解决方案：
1、用自定义的方式启动：python -m solox --host={ip} --port={port}
2、如果用python -m solox，可以按照这里处理：https://www.cnblogs.com/lutt/p/11908226.html

**Comment by lishun001** [comment]
修改hosts已解决
