### ISSUE TITLE
无法完成iOS的性能获取

### ISSUE THREAD

**Issue by 986379041** [smart-test-ti/SoloX#201]
报错提示：
Exception in thread 
perf
:

Traceback (most recent call last):

  File "D:\Program Files\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner

    
self.run()

  File "D:\Program Files\Python\Python310\lib\threading.py", line 953, in run

    
self._target(*self._args, **self._kwargs)

  File "\venv\lib\site-packages\solox\public\iosperf\_perf.py", line 266, in append_data

    
for _type, data in idata:

  File "\venv\lib\site-packages\solox\public\iosperf\_perf.py", line 259, in iter_network_flow

    
"downFlow": (nstat['rx.bytes'] or 0) / 1024,

KeyError
: 
'rx.bytes'
以及'BaseDevice' object has no attribute 'instruments_context'
这两条报错信息

**Comment by rafa0128** [comment]
> 

你是自己更新tidevice了吗？如果是，就先卸载tidevice，再重装solox。
