### ISSUE TITLE
ios16.6 for iPad看起来无法连接

### ISSUE THREAD

**Issue by byhhhh1** [smart-test-ti/SoloX#210]
设备连接失败
连接失败
请检查当前移动设备的是否连接了PC端

[I 230827 23:10:10 common:123] Connected devices: ['00008103-001939CA2162201E']
[E 230827 23:10:10 apis:88] 'Value'
    Traceback (most recent call last):
      File "C:\Users\21720\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\view\apis.py", line 77, in deviceids
        device_detail = d.getDdeviceDetail(deviceId=deviceinfos[0], platform=platform)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\21720\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\common.py", line 182, in getDdeviceDetail
        result['serialno'] = ios_device.get_value("SerialNumber", no_session=True)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
![Uploading Snipaste_2023-08-27_23-13-54.png…]()

      File "C:\Users\21720\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice\_device.py", line 382, in get_value
        return ret['Value']
               ~~~^^^^^^^^^
    KeyError: 'Value'
192.168.124.11 - - [27/Aug/2023 23:10:10] "GET /device/ids?platform=iOS&_=1693149009866 HTTP/1.1" 200 -

**Comment by rafa0128** [comment]
2.7.5修复
