### ISSUE TITLE
python -m solox 无法启动

### ISSUE THREAD

**Issue by Niu-12138** [smart-test-ti/SoloX#219]
![WX20230913-142246](https://github.com/smart-test-ti/SoloX/assets/19486884/47d2e579-f482-4ef8-8e1e-6111cd8c9f8c)
如图，求指点

**Comment by rafa0128** [comment]
能把文本贴贴一下，第一次看到这个错误

**Comment by Niu-12138** [comment]
➜  LoViewGallery git:(main) ✗ python3 -m solox
[I 230914 20:16:06 web:73] hostname:bogon
[W 230914 20:16:06 web:74] config [127.0.0.1 hostname] in /etc/hosts file
[E 230914 20:16:06 web:121] (pid=39948)
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
        return fun(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psutil/_psosx.py", line 503, in connections
        rawlist = cext.proc_connections(self.pid, families, types)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    PermissionError: [Errno 1] Operation not permitted (originated from proc_pidinfo(PROC_PIDLISTFDS) 1/2)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/web.py", line 111, in main
        if listen(port):
           ^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/web.py", line 80, in listen
        net_connections = psutil.net_connections()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psutil/__init__.py", line 2163, in net_connections
        return _psplatform.net_connections(kind)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psutil/_psosx.py", line 248, in net_connections
        cons = Process(pid).connections(kind)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psutil/_psosx.py", line 353, in wrapper
        raise AccessDenied(self.pid, self._name)
    psutil.AccessDenied: (pid=39948)
