### ISSUE TITLE
Unable to obtain FPS value for Android devices 

### ISSUE THREAD

**Issue by cooltaby** [smart-test-ti/SoloX#232]
[BUG]. Unable to get FPS values on Android devices
Tested on Android devices, google pixel 6, Samsung fold and other android devices with different OS, and mobile games.
Errors log:

`[E 231028 20:53:05 fps:327] an exception hanpend in fps _collector_thread , reason unkown!
[D 231028 20:53:05 fps:329] Traceback (most recent call last):
      File "C:\Users\EVM\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 302, in _collector_thread
        refresh_period, new_timestamps = self._get_surfaceflinger_frame_data()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\EVM\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 411, in _get_surfaceflinger_frame_data
        refresh_period = (int(results[0].split('=')[1].strip()) - nanoseconds_per_second) / nanoseconds_per_second
                                     ^^^^^^^^^^^^^^^
    ValueError: invalid literal for int() with base 10: 'now = 666332703981869'

[E 231028 20:53:05 fps:327] an exception hanpend in fps _collector_thread , reason unkown!
[D 231028 20:53:05 fps:329] Traceback (most recent call last):
      File "C:\Users\EVM\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 302, in _collector_thread
        refresh_period, new_timestamps = self._get_surfaceflinger_frame_data()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\EVM\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 411, in _get_surfaceflinger_frame_data
        refresh_period = (int(results[0].split('=')[1].strip()) - nanoseconds_per_second) / nanoseconds_per_second
                                     ^^^^^^^^^^^^^^^
    ValueError: invalid literal for int() with base 10: 'now = 666332807100869'

[E 231028 20:53:05 fps:327] an exception hanpend in fps _collector_thread , reason unkown!`

Note: 
Also tried:
Step1 : You can turn off the 'SurfaceView' switch
Step2 : Set the following settings on your phone： (Developer - GPU rendering mode - adb shell dumpsys gfxinfo)

But still not able to get FPS value. 

@rafa0128

**Comment by rafa0128** [comment]
It looks like old code， show me the version of solox

**Comment by cooltaby** [comment]
![solox version](https://github.com/smart-test-ti/SoloX/assets/12084138/456ec376-31de-485b-9814-a876361b8109)

**Comment by rafa0128** [comment]
it's weird, please reinstall solox and try again，the error code was in old version
