### ISSUE TITLE
Python3.11启动失败

### ISSUE THREAD

**Issue by Ariel08081214** [smart-test-ti/SoloX#239]
D:\workspace>python -m solox
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\solox\__main__.py", line 17, in <module>
    from solox.web import main
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\solox\web.py", line 18, in <module>
    from solox.view.apis import api
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\solox\view\apis.py", line 7, in <module>
    from solox.public.apm import CPU, Memory, Network, FPS, Battery, GPU, Target
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\solox\public\apm.py", line 6, in <module>
    import tidevice
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\tidevice\__init__.py", line 7, in <module>
    from ._device import BaseDevice as Device
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\tidevice\_device.py", line 29, in <module>
    from PIL import Image
  File "D:\developTools\setup\Python\Python311\Lib\site-packages\PIL\Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (D:\developTools\setup\Python\Python311\Lib\site-packages\PIL\__init__.py)

我本地装了3.8、3.11，3.8可以启动低版本的，但是3.11无法启动高版本的，请问怎么解决呢？

**Comment by rafa0128** [comment]
你是不是自己整了pillow这个模块？你卸载pillow后，重装一下solox试试

**Comment by mutexz** [comment]
我本地python3.11版本测试，正常启动，可以试试pip install -U Pillow更新pillow包

**Comment by Ariel08081214** [comment]
@mutexz @rafa0128 尝试了，没用，我换3.12可以了，感谢

**Comment by Ariel08081214** [comment]
@rafa0128 @mutexz  memory部分我去查了，但是CPU中System部分是什么？求解答，感谢

**Comment by mutexz** [comment]
> @rafa0128 @mutexz memory部分我去查了，但是CPU中System部分是什么？求解答，感谢

系统占用的CPU

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/blob/master/DocForAndroid.md
@Ariel08081214 这里都有，注意看文档
