### ISSUE TITLE
升级最新版本2.8.7后在python3.12环境下无法使用

### ISSUE THREAD

**Issue by MartinDong** [smart-test-ti/SoloX#251]
python3  -m solox
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/solox/__main__.py", line 17, in <module>
    from solox.web import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/solox/web.py", line 9, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/packages/urllib3/__init__.py", line 24, in <module>
    from .poolmanager import PoolManager, ProxyManager, proxy_from_url
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/packages/urllib3/poolmanager.py", line 14, in <module>
    from ._collections import RecentlyUsedContainer
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/packages/urllib3/_collections.py", line 7, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/collections/__init__.py)

**Comment by rafa0128** [comment]
应该你电脑的requests这个模块有点老了，自己升级一下看看
