### ISSUE TITLE
不懂就问：我的 iOS 设备除了电池，其余信息均采集不了，请问是哪里设置错了嘛？

### ISSUE THREAD

**Issue by JIUJIUs** [smart-test-ti/SoloX#254]
SoloX ：2.8.6
Python ：3.10.11
System：WIndows 11
Browser：Chrome
Device：iPhone Xs Max；iPhone11,6；iOS 15.7.1；
              iPhone 15 Pro Max；iPhone16,2；iOS 17.2.1；

![image](https://github.com/smart-test-ti/SoloX/assets/61548656/25d315dc-e13b-4c7d-b4ee-1bbf06d28820)

![image](https://github.com/smart-test-ti/SoloX/assets/61548656/f42927f1-a372-46e4-9cc8-3a7137e1b3b8)

**Comment by rafa0128** [comment]
主要看终端报错日志，不支持ios17的

**Comment by JIUJIUs** [comment]
> 主要看终端报错日志，不支持ios17的

好，我用 iPhone Xs Max 给你份日志，请问怎么获取？

**Comment by JIUJIUs** [comment]
> 主要看终端报错日志，不支持ios17的

是不是这个？

192.168.10.209 - - [22/Dec/2023 11:14:56] "GET /apm/fps?model=normal&platform=iOS&pkgname=cn.adidas.confirmed.app&device=00008020-0019583622D8002E&surv=false&_=1703214845227 HTTP/1.1" 200 -
192.168.10.209 - - [22/Dec/2023 11:14:56] "GET /apm/battery?platform=iOS&device=00008020-0019583622D8002E&_=1703214845241 HTTP/1.1" 200 -
192.168.10.209 - - [22/Dec/2023 11:14:57] "GET /apm/battery?platform=iOS&device=00008020-0019583622D8002E&_=1703214845243 HTTP/1.1" 200 -
[E 231222 11:14:57 apis:254] get memory data failed
[E 231222 11:14:57 apis:255] ImageMountFailed
    Traceback (most recent call last):
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\view\apis.py", line 251, in getMEM
        totalPass, nativePass, dalvikPass = mem.getProcessMem()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\apm.py", line 172, in getProcessMem
        totalPass, nativePass, dalvikPass = self.getAndroidMem() if self.platform == Platform.Android else self.getiOSMem()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\apm.py", line 165, in getiOSMem
        totalPass = round(float(apm.getPerformance(apm.memory)), 2)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\apm.py", line 416, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\_iosPerf.py", line 320, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
        self._ins = d.connect_instruments()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed

**Comment by rafa0128** [comment]
换mac测ios吧，windows这个通信不稳定。不过如果又看到类似https://tool.appetizer.io/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/17.0.zip下载失败的日志，就是不支持这个系统

**Comment by JIUJIUs** [comment]
> 换mac测ios吧，windows这个通信不稳定。不过如果又看到类似[https://tool.appetizer.io/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/17.0.zip下载失败的日志，就是不支持这个系统](https://tool.appetizer.io/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/17.0.zip%E4%B8%8B%E8%BD%BD%E5%A4%B1%E8%B4%A5%E7%9A%84%E6%97%A5%E5%BF%97%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%B8%8D%E6%94%AF%E6%8C%81%E8%BF%99%E4%B8%AA%E7%B3%BB%E7%BB%9F)

收到！

**Comment by lezhi12** [comment]
> > 主要看终端报错日志，不支持ios17的
> 
> 是不是这个？
> 
> `192.168.10.209 - - [22/Dec/2023 11:14:56] "GET /apm/fps?model=normal&platform=iOS&pkgname=cn.adidas.confirmed.app&device=00008020-0019583622D8002E&surv=false&_=1703214845227 HTTP/1.1" 200 - 192.168.10.209 - - [22/Dec/2023 11:14:56] "GET /apm/battery?platform=iOS&device=00008020-0019583622D8002E&_=1703214845241 HTTP/1.1" 200 - 192.168.10.209 - - [22/Dec/2023 11:14:57] "GET /apm/battery?platform=iOS&device=00008020-0019583622D8002E&_=1703214845243 HTTP/1.1" 200 - [E 231222 11:14:57 apis:254] get memory data failed [E 231222 11:14:57 apis:255] ImageMountFailed Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice_device.py", line 483, in start_service return self._unsafe_start_service(name) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice_device.py", line 502, in _unsafe_start_service raise MuxServiceError(error) tidevice.exceptions.MuxServiceError: InvalidService
> 
> ```
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\view\apis.py", line 251, in getMEM
>     totalPass, nativePass, dalvikPass = mem.getProcessMem()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\apm.py", line 172, in getProcessMem
>     totalPass, nativePass, dalvikPass = self.getAndroidMem() if self.platform == Platform.Android else self.getiOSMem()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\apm.py", line 165, in getiOSMem
>     totalPass = round(float(apm.getPerformance(apm.memory)), 2)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\apm.py", line 416, in getPerformance
>     perf_value = perf.start(self.pkgName, callback=self.callback)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\_iosPerf.py", line 320, in start
>     self._rp = RunningProcess(self._d, bundle_id)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
>     self._ins = d.connect_instruments()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
>     conn = self.start_service(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 485, in start_service
>     self.mount_developer_image()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
>     self.imagemounter.mount(image_path, signature_path)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
>     return self.mount_fileobj(image_reader, image_size, signature_content)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
>     self._check_error(ret)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
>     raise MuxError(ret['Error'])
> tidevice.exceptions.MuxError: ImageMountFailed`
> ```

感觉从日志上看，是ImageMountFaild，尝试去user目录下找到.tidevice目录，找一下".tidevice"目录，看看里面有没有15的image。比如15.xx.zip，如果没有，那就是这个原因导致的mount失败，下载一个15的镜像放到这个目录里，再执行solox试试还会不会出错
