### ISSUE TITLE
大佬试了新版2.8.8 fps就只有1了

### ISSUE THREAD

**Issue by katyhudson** [smart-test-ti/SoloX#257]
[I 240105 17:18:19 web:103] Running on http://192.168.43.186:50003/?platform=Android&lan=en (Press CTRL+C to quit)
[I 240105 17:18:20 common:74] Connected devices: ['000001368c79484e(V1962A)']
[I 240105 17:18:32 common:227] Clean up useless files ...
[I 240105 17:18:32 common:864] stop scrcpy process
[E 240105 17:18:33 common:873] process PID not found (pid=18684)
    Traceback (most recent call last):
      File "D:\Python311\Lib\site-packages\psutil\_pswindows.py", line 694, in wrapper
        return fun(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\psutil\_pswindows.py", line 948, in create_time
        user, system, created = cext.proc_times(self.pid)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
    ProcessLookupError: [Errno 3] assume no such process (originated from OpenProcess -> ERROR_INVALID_PARAMETER)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Python311\Lib\site-packages\psutil\__init__.py", line 361, in _init
        self.create_time()
      File "D:\Python311\Lib\site-packages\psutil\__init__.py", line 719, in create_time
        self._create_time = self._proc.create_time()
                            ^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\psutil\_pswindows.py", line 696, in wrapper
        raise convert_oserror(err, pid=self.pid, name=self._name)
    psutil.NoSuchProcess: process no longer exists (pid=18684)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Python311\Lib\site-packages\solox\public\common.py", line 868, in stop_record
        p = psutil.Process(pid)
            ^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\psutil\__init__.py", line 332, in __init__
        self._init(pid)
      File "D:\Python311\Lib\site-packages\psutil\__init__.py", line 373, in _init
        raise NoSuchProcess(pid, msg='process PID not found')
    psutil.NoSuchProcess: process PID not found (pid=18684)
![image](https://github.com/smart-test-ti/SoloX/assets/24410664/1b838e28-1d4f-4815-814a-df143ae95878)

**Comment by rafa0128** [comment]
这个报错没有关系，多试几下

**Comment by katyhudson** [comment]
> 这个报错没有关系，多试几下 还有你是啥app和啥场景？

也是我们公司的软件，场景就是左滑。这个包好像fps值最高就3

**Comment by rafa0128** [comment]
个位数一般就是系统没有数据，你这台设备不兼容

**Comment by katyhudson** [comment]
> 个位数一般就是系统没有数据，你这台设备不兼容

设备不变，但是app变了 还是证券app。

**Comment by rafa0128** [comment]
没有明显报错我这边不管了，兼容太累了。上周兼容那哥们的设备把我累死。

**Comment by katyhudson** [comment]
我明天再测试测试
