### ISSUE TITLE
iOS一直采集不上数据是咋回事

### ISSUE THREAD

**Issue by qangcheng** [smart-test-ti/SoloX#268]
[E 240228 09:41:41 apis:333] get network data failed
[E 240228 09:41:41 apis:334] ImageMountFailed
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "D:\python\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\python\lib\site-packages\solox\view\apis.py", line 330, in getNetWorkData
        data = network.getNetWorkData(wifi=wifi,noLog=False)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 361, in getNetWorkData
        sendNum, recNum = self.getAndroidNet(wifi) if self.platform == Platform.Android else self.getiOSNet()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 354, in getiOSNet
        apm_data = apm.getPerformance(apm.network)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 464, in getPerformance
        perf.start(self.pkgName, callback=self.callback)
      File "D:\python\lib\site-packages\solox\public\iosperf\_perf.py", line 304, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "D:\python\lib\site-packages\solox\public\iosperf\_perf.py", line 37, in __init__
        self._ins = d.connect_instruments()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "D:\python\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/network?model=normal&platform=iOS&pkgname=com.stonemobile.youstar&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&wifi_switch=false&process=&_=1709084453663 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453681 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453683 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453684 HTTP/1.1" 200 -
[E 240228 09:41:41 apis:249] get memory data failed
[E 240228 09:41:41 apis:250] ImageMountFailed
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "D:\python\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\python\lib\site-packages\solox\view\apis.py", line 246, in getMemory
        totalPass, swapPass = mem.getProcessMemory()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 227, in getProcessMemory
        totalPass, swapPass = self.getAndroidMemory() if self.platform == Platform.Android else self.getiOSMemory()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 221, in getiOSMemory
        totalPass = round(float(apm.getPerformance(apm.memory)), 2)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 470, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 325, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
        self._ins = d.connect_instruments()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "D:\python\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.stonemobile.youstar&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&process=&_=1709084453659 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453685 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:41] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453687 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453688 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453689 HTTP/1.1" 200 -
[E 240228 09:41:42 apis:408] ImageMountFailed
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "D:\python\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\python\lib\site-packages\solox\view\apis.py", line 405, in getGpu
        final = gpu.getGPU()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 431, in getGPU
        gpu = apm.getPerformance(apm.gpu)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 470, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 325, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
        self._ins = d.connect_instruments()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "D:\python\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/gpu?pkgname=com.stonemobile.youstar&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453667 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453690 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453692 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453693 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453694 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:42] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453695 HTTP/1.1" 200 -
[E 240228 09:41:43 apis:370] get fps failed
[E 240228 09:41:43 apis:371] ImageMountFailed
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "D:\python\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\python\lib\site-packages\solox\view\apis.py", line 367, in getFps
        fps, jank = fps_monitor.getFPS()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 421, in getFPS
        fps, jank = self.getAndroidFps(noLog) if self.platform == Platform.Android else self.getiOSFps(noLog)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 413, in getiOSFps
        fps = int(apm.getPerformance(apm.fps))
      File "D:\python\lib\site-packages\solox\public\apm.py", line 470, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 325, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
        self._ins = d.connect_instruments()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "D:\python\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.stonemobile.youstar&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&surv=false&_=1709084453673 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453696 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453698 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453699 HTTP/1.1" 200 -
[E 240228 09:41:43 apis:210] get cpu failed
[E 240228 09:41:43 apis:211] ImageMountFailed
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "D:\python\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\python\lib\site-packages\solox\view\apis.py", line 207, in getCpuRate
        appCpuRate, systemCpuRate = cpu.getCpuRate()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 132, in getCpuRate
        appCpuRate, systemCpuRate = self.getAndroidCpuRate(noLog) if self.platform == Platform.Android else self.getiOSCpuRate(noLog)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 122, in getiOSCpuRate
        appCpuRate = round(float(apm.getPerformance(apm.cpu)[0]), 2)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 470, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 325, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "D:\python\lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
        self._ins = d.connect_instruments()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "D:\python\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/cpu?model=normal&platform=iOS&pkgname=com.stonemobile.youstar&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&process=&_=1709084453677 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453700 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453702 HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2024 09:41:43] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453703 HTTP/1.1" 200 -
Process SpawnPoolWorker-2:
^CTraceback (most recent call last):
  File "D:\python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "D:\python\lib\multiprocessing\queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "D:\python\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\python\lib\multiprocessing\connection.py", line 305, in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
KeyboardInterrupt
192.168.1.25 - - [28/Feb/2024 09:41:44] "GET /apm/battery?platform=iOS&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&_=1709084453704 HTTP/1.1" 200 -
[E 240228 09:41:44 apis:333] get network data failed
[E 240228 09:41:44 apis:334] ImageMountFailed
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
      File "D:\python\lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\python\lib\site-packages\solox\view\apis.py", line 330, in getNetWorkData
        data = network.getNetWorkData(wifi=wifi,noLog=False)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 361, in getNetWorkData
        sendNum, recNum = self.getAndroidNet(wifi) if self.platform == Platform.Android else self.getiOSNet()
      File "D:\python\lib\site-packages\solox\public\apm.py", line 354, in getiOSNet
        apm_data = apm.getPerformance(apm.network)
      File "D:\python\lib\site-packages\solox\public\apm.py", line 464, in getPerformance
        perf.start(self.pkgName, callback=self.callback)
      File "D:\python\lib\site-packages\solox\public\iosperf\_perf.py", line 304, in start
        self._rp = RunningProcess(self._d, bundle_id)
      File "D:\python\lib\site-packages\solox\public\iosperf\_perf.py", line 37, in __init__
        self._ins = d.connect_instruments()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
      File "D:\python\lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "D:\python\lib\site-packages\tidevice\_device.py", line 662, in mount_developer_image
        self.imagemounter.mount(image_path, signature_path)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
        return self.mount_fileobj(image_reader, image_size, signature_content)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
        self._check_error(ret)
      File "D:\python\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
        raise MuxError(ret['Error'])
    tidevice.exceptions.MuxError: ImageMountFailed
192.168.1.25 - - [28/Feb/2024 09:41:44] "GET /apm/network?model=normal&platform=iOS&pkgname=com.stonemobile.youstar&device=f22a54a16eab576d0df77482ce3f38e6681d97cd&wifi_switch=false&process=&_=1709084453682 HTTP/1.1" 200 -

**Comment by qangcheng** [comment]
15的系统

**Comment by rafa0128** [comment]
换mac执行吧，windows测ios不稳定
