### ISSUE TITLE
Unable to get GPU data on Pixel devices

### ISSUE THREAD

**Issue by TrungDq1813** [smart-test-ti/SoloX#286]
I'm unable to measure GPU data for Pixel devices. The other stats work fine.
Testing with:
- Pixel 3XL (Android 12)
- Pixel 6XL (Android 14)
Here's the error logs:
```
[E 240626 11:35:04 apis:449] invalid literal for int() with base 10: ''
    Traceback (most recent call last):
      File "C:\Python311\Lib\site-packages\solox\view\apis.py", line 446, in getGpu
        value = gpu.getGPU()
                ^^^^^^^^^^^^
      File "C:\Python311\Lib\site-packages\solox\public\apm.py", line 486, in getGPU
        gpu = self.getAndroidGpuRate() if self.platform == Platform.Android else self.getiOSGpuRate()
              ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Python311\Lib\site-packages\solox\public\apm.py", line 477, in getAndroidGpuRate
        gpu = round(float(int(result.split(' ')[0]) / int(result.split(' ')[1])) * 100, 2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: invalid literal for int() with base 10: ''
10.0.144.113 - - [26/Jun/2024 11:35:04] "GET /apm/gpu?platform=Android&pkgname=com.immutable.guildofguardians&device=8B6Y0UPN8(Pixel%203%20XL)&_=1719376432325 HTTP/1.1" 200 -
10.0.144.113 - - [26/Jun/2024 11:35:04] "GET /apm/mem?model=normal&platform=Android&pkgname=com.immutable.guildofguardians&device=8B6Y0UPN8(Pixel%203%20XL)&process=26412%3Acom.immutable.guildofguardians&_=1719376432327 HTTP/1.1" 200 -
10.0.144.113 - - [26/Jun/2024 11:35:04] "GET /apm/battery?platform=Android&device=8B6Y0UPN8(Pixel%203%20XL)&_=1719376432328 HTTP/1.1" 200 -
```
![image](https://github.com/smart-test-ti/SoloX/assets/39461503/3033ad16-d8c7-4407-a629-b1e87e26b75d)
![image](https://github.com/smart-test-ti/SoloX/assets/39461503/6e9e657b-5ee6-4d0d-9b2c-47c0b711aa4b)

**Comment by rafa0128** [comment]
only supports some Adreno GPU phones
