### ISSUE TITLE
ios15.5系统，solox只能收集到电量，其他指标都是0 怎么解决呢？

### ISSUE THREAD

**Issue by chenxupeng** [smart-test-ti/SoloX#297]
![image](https://github.com/user-attachments/assets/c22b5496-ad93-48e8-b578-cae87b9f9cd7)

**Comment by chenxupeng** [comment]
[E 241209 17:07:06 apis:409] get fps failed
[E 241209 17:07:06 apis:410] 404 Client Error: Not Found for url: https://github.com/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/15.5.zip
    Traceback (most recent call last):
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_device.py", line 483, in start_service
        return self._unsafe_start_service(name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_device.py", line 502, in _unsafe_start_service
        raise MuxServiceError(error)
    tidevice.exceptions.MuxServiceError: InvalidService

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\测试工具\venv\Lib\site-packages\solox\view\apis.py", line 406, in getFps
        fps, jank = fps_monitor.getFPS()
                    ^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\solox\public\apm.py", line 465, in getFPS
        fps, jank = self.getAndroidFps(noLog) if self.platform == Platform.Android else self.getiOSFps(noLog)
                                                                                        ^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\solox\public\apm.py", line 457, in getiOSFps
        fps = int(apm.getPerformance(apm.fps))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\solox\public\apm.py", line 671, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\solox\public\_iosPerf.py", line 325, in start
        self._rp = RunningProcess(self._d, bundle_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\solox\public\_iosPerf.py", line 36, in __init__
        self._ins = d.connect_instruments()
                    ^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_device.py", line 792, in connect_instruments
        conn = self.start_service(
               ^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_device.py", line 485, in start_service
        self.mount_developer_image()
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_device.py", line 659, in mount_developer_image
        with self._request_developer_image_dir() as _dir: #, signature_path:
      File "C:\Python311\Lib\contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_device.py", line 611, in _request_developer_image_dir
        image_zip_path = cache_developer_image(version)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_imagemounter.py", line 87, in cache_developer_image
        raise err
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_imagemounter.py", line 75, in cache_developer_image
        _urlretrieve(url, image_zip_path)
      File "F:\测试工具\venv\Lib\site-packages\decorator.py", line 232, in fun
        return caller(func, *(extras + args), **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\retry\api.py", line 73, in retry_decorator
        return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\测试工具\venv\Lib\site-packages\retry\api.py", line 33, in __retry_internal
        return f()
               ^^^
      File "F:\测试工具\venv\Lib\site-packages\tidevice\_imagemounter.py", line 30, in _urlretrieve
        r.raise_for_status()
      File "F:\测试工具\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/15.5.zip

**Comment by zhefengzhang** [comment]
我也遇到同样问题，等待解决

**Comment by gaige8934** [comment]
手机要开启debug模式，应该 开启这个就好了。

**Comment by rafa0128** [comment]
参考：https://github.com/smart-test-ti/SoloX/issues/271

**Comment by chenxupeng** [comment]
已解决 感谢~ @rafa0128
