### ISSUE TITLE
无法启动Solox

### ISSUE THREAD

**Issue by Wangdenan** [smart-test-ti/SoloX#67]
启动日志：
Traceback (most recent call last):
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\site-packages\solox\__main__.py", line 2, in <module>
    from solox.web import main
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\site-packages\solox\web.py", line 12, in <module>
    from solox.view.apis import api
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\site-packages\solox\view\apis.py", line 4, in <module>
    from flask import request, make_response
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\__init__.py", line 4, in <module>
    from . import json as json
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 8, in <module>
    from ..globals import current_app
  File "C:\Users\wangdenan1\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\globals.py", line 57, in <module>
    _cv_app, unbound_message=_no_app_msg
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
麻烦大佬看看，感谢！

**Comment by rafa0128** [comment]
> 

之前自己有装过flask吗？看看这两个模块的版本flask、Werkzeug，建议都卸载了，重装一遍solox（会自动带适合的版本）

**Comment by Wangdenan** [comment]
已解决，谢谢
